# Generated by Django 3.2.13 on 2022-12-08 19:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arduino',
            fields=[
                ('arduino_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=50, verbose_name='Arduino')),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoTempo',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('hora_requisicao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora da Solicitação')),
                ('arduino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arduinos', to='dashboard.arduino')),
            ],
        ),
    ]
