# Generated by Django 3.2.13 on 2022-12-08 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SolicitacaoTempo',
            new_name='SolicitacaoTemperatura',
        ),
    ]
