# Generated by Django 4.1.5 on 2023-01-18 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_sensordata_delete_measurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacaotemperatura',
            name='arduino',
        ),
        migrations.DeleteModel(
            name='Arduino',
        ),
        migrations.DeleteModel(
            name='SolicitacaoTemperatura',
        ),
    ]
