# Generated by Django 4.1.5 on 2023-01-20 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_solicitacaotemperatura_arduino_delete_arduino_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SensorData',
        ),
    ]
