# Generated by Django 4.1.5 on 2023-01-22 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemperatureReading',
        ),
    ]
