# Generated by Django 4.1.5 on 2023-01-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0012_delete_temperaturereading'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThingSpeakData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.IntegerField()),
                ('field1', models.FloatField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
