# Generated by Django 4.1.5 on 2023-01-22 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thingspeakdata',
            name='channel_id',
        ),
    ]
