# Generated by Django 4.1.5 on 2023-01-22 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_thingspeakdata_channel_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThingSpeakData',
        ),
    ]
