# Generated by Django 4.1.5 on 2023-01-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureData2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('temperature', models.FloatField()),
            ],
        ),
    ]
