# Generated by Django 4.1.5 on 2023-01-22 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_temperaturedata2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemperatureData2',
        ),
    ]
