# Generated by Django 4.1.5 on 2023-01-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_delete_temperaturedata2'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperaturedata',
            name='channel_id',
            field=models.IntegerField(default=0),
        ),
    ]
