# Generated by Django 4.1.5 on 2023-01-22 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_temperaturedata_channel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperaturedata',
            name='channel_id',
        ),
    ]
