# Generated by Django 4.1.5 on 2023-01-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_remove_temperaturedata_channel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturedata',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
