# Generated by Django 4.1.5 on 2023-02-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_alter_temperaturedata_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturedata',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
