# Generated by Django 4.1.5 on 2023-02-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_alter_temperaturedata_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturedata',
            name='temperature',
            field=models.CharField(max_length=50),
        ),
    ]
